plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = '1.0.0'
group = 'com.worldbattles.commands'
base { archivesName = 'worldbattles-teleport-metiers' }
java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
    copyIdeResources = true
    runs {
        server {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'info'
            args '--nogui'
            mods { worldbattlescommands { source sourceSets.main } }
        }
    }
}

repositories { mavenCentral() }
dependencies { minecraft 'net.minecraftforge:forge:1.20.1-47.3.0' }

jar {
    manifest {
        attributes([
            'Specification-Title': 'WorldBattles Teleportation et Pause Metiers',
            'Specification-Vendor': 'WorldBattles',
            'Specification-Version': '1',
            'Implementation-Title': project.name,
            'Implementation-Version': project.version,
            'Implementation-Vendor': 'WorldBattles'
        ])
    }
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
