modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="worldbattlesarenas"
version="${file.jarVersion}"
displayName="WorldBattles Arenas"
description='''Zombies - limited test build. No inventory clear or structure reset.'''
[[dependencies.worldbattlesarenas]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.worldbattlesarenas]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"
