plugins { id 'net.minecraftforge.gradle' version '[6.0,6.2)' }
group = 'com.worldbattles'
version = '1.2.1'
base { archivesName = 'worldbattles-companion' }
java.toolchain.languageVersion = JavaLanguageVersion.of(17)
minecraft { mappings channel: 'official', version: '1.20.1'; runs { server { workingDirectory project.file('run') } } }
repositories { mavenCentral() }
dependencies { minecraft 'net.minecraftforge:forge:1.20.1-47.3.0' }
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
